var data = {
  states: [
    {
      name: "Alabama",
      capital: "Montgomery",
      bird: "Yellowhammer",
      flower: "Camellia",
      area: 52419,
      order: 22,
      date: "December 14, 1819",
      nickname: "Yellowhammer State",
      motto: "Audemus jura nostra defendere (We dare defend our rights)",
      location: "alabama_location.jpg",
      flag: "alabama_state_flag.gif",
      county: "alabama_county.gif",
      terrain: "alabama_terrain.gif"
    },
    {
      name: "Alaska",
      capital: "Juneau",
      bird: "Willow Ptarmigan",
      flower: "Forget Me Not",
      area: 663267,
      order: 49,
      date: "January 3, 1959",
      nickname: "The Last Frontier",
      motto: "The Last Frontier",
      location: "alaska_location.jpg",
      flag: "alaska_state_flag.gif",
      county: "alaska_county.gif",
      terrain: "alaska_terrain.gif"
    },
    {
      name: "Arizona",
      capital: "Phoenix",
      bird: "Cactus Wren",
      flower: "Saguaro Cactus Blossom",
      area: 113998,
      order: 48,
      date: "February 14, 1912",
      nickname: "The Grand Canyon State",
      motto: "Ditat Deus (God enriches)",
      location: "arizona_location.jpg",
      flag: "arizona_state_flag.jpg",
      county: "arizona_county.gif",
      terrain: "arizona_terrain.gif"
    },
    {
      name: "Arkansas",
      capital: "Little Rock",
      bird: "Mockingbird",
      flower: "Apple Blossom",
      area: 53179,
      order: 25,
      date: "June 15, 1836",
      nickname: "The Natural State",
      motto: "Regnat populus (The people rule)",
      location: "arkansas_location.jpg",
      flag: "arkansas_state_flag.jpg",
      county: "arkansas_county.gif",
      terrain: "arkansas_terrain.gif"
    },
    {
      name: "California",
      capital: "Sacramento",
      bird: "California Valley Quail",
      flower: "Golden Poppy",
      area: 163696,
      order: 31,
      date: "September 9, 1850",
      nickname: "Golden State",
      motto: "Eureka (I have found it)",
      location: "california_location.jpg",
      flag: "california_state_flag.gif",
      county: "california_county.gif",
      terrain: "california_terrain.gif"
    },
    {
      name: "Colorado",
      capital: "Denver",
      bird: "Lark Bunting",
      flower: "Rocky Mountain Columbine",
      area: 104094,
      order: 38,
      date: "August 1, 1876",
      nickname: "Centennial State",
      motto: "Nil sine numine (Nothing without the Deity)",
      location: "colorado_location.jpg",
      flag: "colorado_state_flag.gif",
      county: "colorado_county.gif",
      terrain: "colorado_terrain.gif"
    },
    {
      name: "Connecticut",
      capital: "Hartford",
      bird: "Robin",
      flower: "Mountain Laurel",
      area: 5543,
      order: 5,
      date: "January 9, 1788",
      nickname: "Constitution State",
      motto: "Qui transtulit sustinet (He who transplanted sustains)",
      location: "connecticut_location.jpg",
      flag: "connecticut_state_flag.jpg",
      county: "connecticut_county.gif",
      terrain: "connecticut_terrain.gif"
    },
    {
      name: "Delaware",
      capital: "Dover",
      bird: "Blue Hen Chicken",
      flower: "Peach Blossom",
      area: 2489,
      order: 1,
      date: "December 7, 1787",
      nickname: "Diamond State; First State",
      motto: "Liberty and Independence",
      location: "delaware_location.jpg",
      flag: "delaware_state_flag.gif",
      county: "delaware_county.gif",
      terrain: "delaware_terrain.gif"
    },
    {
      name: "Florida",
      capital: "Tallahassee",
      bird: "Mockingbird",
      flower: "Orange Blossom",
      area: 65755,
      order: 27,
      date: "March 3, 1845",
      nickname: "Sunshine State",
      motto: "In God We Trust",
      location: "florida_location.jpg",
      flag: "florida_state_flag.jpg",
      county: "florida_county.gif",
      terrain: "florida_terrain.gif"
    },
    {
      name: "Georgia",
      capital: "Atlanta",
      bird: "Brown Thrasher",
      flower: "Cherokee Rose",
      area: 59425,
      order: 4,
      date: "January 2, 1788",
      nickname: "Peach State; Empire State of the South",
      motto: "Wisdom, justice, and moderation",
      location: "georgia_location.jpg",
      flag: "georgia_state_flag.jpg",
      county: "georgia_county.gif",
      terrain: "georgia_terrain.gif"
    },
    {
      name: "Hawaii",
      capital: "Honolulu",
      bird: "Nene",
      flower: "Hibiscus",
      area: 10931,
      order: 50,
      date: "August 21, 1959",
      nickname: "Aloha State",
      motto: "Ua mau ke ea o ka aina i ka pono (The life of the land is perpetuated in righteousness)",
      location: "hawaii_location.jpg",
      flag: "hawaii_state_flag.gif",
      county: "hawaii_county.gif",
      terrain: "hawaii_terrain.gif"
    },
    {
      name: "Idaho",
      capital: "Boise",
      bird: "Mountain Bluebird",
      flower: "Syringa",
      area: 83570,
      order: 43,
      date: "July 3, 1890",
      nickname: "Gem State",
      motto: "Esto perpetua (Let it be perpetual)",
      location: "idaho_location.jpg",
      flag: "idaho_state_flag.jpg",
      county: "idaho_county.gif",
      terrain: "idaho_terrain.gif"
    },
    {
      name: "Illinois",
      capital: "Springfield",
      bird: "Cardinal",
      flower: "Violet",
      area: 57914,
      order: 21,
      date: "December 3, 1818",
      nickname: "Prairie State",
      motto: "State sovereignty, national union",
      location: "illinois_location.jpg",
      flag: "illinois_state_flag.jpg",
      county: "illinois_county.gif",
      terrain: "illinois_terrain.gif"
    },
    {
      name: "Indiana",
      capital: "Indianapolis",
      bird: "Cardinal",
      flower: "Peony",
      area: 36418,
      order: 19,
      date: "December 11, 1816",
      nickname: "Hoosier State",
      motto: "The Crossroads of America",
      location: "indiana_location.jpg",
      flag: "indiana_state_flag.gif",
      county: "indiana_county.gif",
      terrain: "indiana_terrain.gif"
    },
    {
      name: "Iowa",
      capital: "Des Moines",
      bird: "Eastern Goldfinch",
      flower: "Wild Rose",
      area: 56272,
      order: 29,
      date: "December 28, 1846",
      nickname: "Hawkeye State",
      motto: "Our liberties we prize and our rights we will maintain",
      location: "iowa_location.jpg",
      flag: "iowa_state_flag.jpg",
      county: "iowa_county.gif",
      terrain: "iowa_terrain.gif"
    },
    {
      name: "Kansas",
      capital: "Topeka",
      bird: "Western Meadowlark",
      flower: "Sunflower",
      area: 82277,
      order: 34,
      date: "January 29, 1861",
      nickname: "Sunflower State; Jayhawk State",
      motto: "Ad astra per aspera (To the stars through difficulties)",
      location: "kansas_location.jpg",
      flag: "kansas_state_flag.jpg",
      county: "kansas_county.gif",
      terrain: "kansas_terrain.gif"
    },
    {
      name: "Kentucky",
      capital: "Frankfort",
      bird: "Cardinal",
      flower: "Goldenrod",
      area: 40409,
      order: 15,
      date: "June 1, 1792",
      nickname: "Bluegrass State",
      motto: "Sunflower State; Jayhawk State",
      location: "kentucky_location.jpg",
      flag: "kentucky_state_flag.jpg",
      county: "kentucky_county.gif",
      terrain: "kentucky_terrain.gif"
    },
    {
      name: "Louisiana",
      capital: "Baton Rouge",
      bird: "Eastern Brown Pelican",
      flower: "Magnolia",
      area: 51840,
      order: 18,
      date: "April 30, 1812",
      nickname: "Pelican State",
      motto: "Union, justice, confidence",
      location: "louisiana_location.jpg",
      flag: "louisiana_state_flag.jpg",
      county: "louisiana_county.gif",
      terrain: "louisiana_terrain.gif"
    },
    {
      name: "Maine",
      capital: "Augusta",
      bird: "Chickadee",
      flower: "White Pine Cone and Tassel",
      area: 35385,
      order: 23,
      date: "March 15, 1820",
      nickname: "Pine Tree State",
      motto: "Dirigo (I lead)",
      location: "maine_location.jpg",
      flag: "maine_state_flag.jpg",
      county: "maine_county.gif",
      terrain: "maine_terrain.gif"
    },
    {
      name: "Maryland",
      capital: "Annapolis",
      bird: "Baltimore Oriole",
      flower: "Black-Eyed Susan",
      area: 12407,
      order: 7,
      date: "April 28, 1788",
      nickname: "Free State; Old Line State",
      motto: "Fatti maschii, parole femine (Manly deeds, womanly words)",
      location: "maryland_location.jpg",
      flag: "maryland_state_flag.jpg",
      county: "maryland_county.gif",
      terrain: "maryland_terrain.gif"
    },
    {
      name: "Massachusetts",
      capital: "Boston",
      bird: "Chickadee",
      flower: "Mayflower",
      area: 10555,
      order: 6,
      date: "February 6, 1788",
      nickname: "Bay State; Old Colony State",
      motto: "Ense petit placidam sub libertate quietem (By the sword we seek peace, but peace only under liberty)",
      location: "massachusetts_location.jpg",
      flag: "massachusetts_state_flag.jpg",
      county: "massachusetts_county.gif",
      terrain: "massachusetts_terrain.gif"
    },
    {
      name: "Michigan",
      capital: "Lansing",
      bird: "American Robin",
      flower: "Apple Blossom",
      area: 96716,
      order: 26,
      date: "January 26, 1837",
      nickname: "Wolverine State",
      motto: "Si quaeris peninsulam amoenam circumspice (If you seek a pleasant peninsula, look about you)",
      location: "michigan_location.jpg",
      flag: "michigan_state_flag.jpg",
      county: "michigan_county.gif",
      terrain: "michigan_terrain.gif"
    },
    {
      name: "Minnesota",
      capital: "St. Paul",
      bird: "Common Loon",
      flower: "Lady Slipper",
      area: 86939,
      order: 32,
      date: "May 11, 1858",
      nickname: "North Star State; Gopher State; Land of 10,000 Lakes",
      motto: "L'Étoile du Nord (The star of the North)",
      location: "minnesota_location.jpg",
      flag: "minnesota_state_flag.jpg",
      county: "minnesota_county.gif",
      terrain: "minnesota_terrain.gif"
    },
    {
      name: "Mississippi",
      capital: "Jackson",
      bird: "Mockingbird",
      flower: "Bloom of the Magnolia or Evergreen Magnolia",
      area: 48430,
      order: 20,
      date: "December 10, 1817",
      nickname: "Magnolia State",
      motto: "Virtute et armis (By valor and arms)",
      location: "mississippi_location.jpg",
      flag: "mississippi_state_flag.jpg",
      county: "mississippi_county.gif",
      terrain: "mississippi_terrain.gif"
    },
    {
      name: "Missouri",
      capital: "Jefferson City",
      bird: "Bluebird",
      flower: "Hawthorn",
      area: 69704,
      order: 24,
      date: "August 10, 1821",
      nickname: "Show-me State",
      motto: "Salus populi suprema lex esto (Let the welfare of the people be the supreme law)",
      location: "missouri_location.jpg",
      flag: "missouri_state_flag.jpg",
      county: "missouri_county.gif",
      terrain: "missouri_terrain.gif"
    },
    {
      name: "Montana",
      capital: "Helena",
      bird: "Western Meadowlark",
      flower: "Bitterroot",
      area: 147042,
      order: 41,
      date: "November 8, 1889",
      nickname: "Treasure State",
      motto: "Oro y plata (Gold and silver)",
      location: "montana_location.jpg",
      flag: "montana_state_flag.jpg",
      county: "montana_county.gif",
      terrain: "montana_terrain.gif"
    },
    {
      name: "Nebraska",
      capital: "Lincoln",
      bird: "Western Meadowlark",
      flower: "Goldenrod",
      area: 77354,
      order: 37,
      date: "March 1, 1867",
      nickname: "Cornhusker State; Beef State",
      motto: "Equality before the law",
      location: "nebraska_location.jpg",
      flag: "nebraska_state_flag.jpg",
      county: "nebraska_county.gif",
      terrain: "nebraska_terrain.gif"
    },
    {
      name: "Nevada",
      capital: "Carson City",
      bird: "Mountain Bluebird",
      flower: "Sagebrush",
      area: 110561,
      order: 36,
      date: "October 31, 1864",
      nickname: "Sagebrush State; Silver State; Battle Born State",
      motto:"All For Our Country and Battle Born",
      location: "nevada_location.jpg",
      flag: "nevada_state_flag.jpg",
      county: "nevada_county.gif",
      terrain: "nevada_terrain.gif"
    },
    {
      name: "New Hampshire",
      capital: "Concord",
      bird: "Purple Finch",
      flower: "Purple Lilac",
      area: 9350,
      order: 9,
      date: "June 21, 1788",
      nickname: "Granite State",
      motto: "Live Free or Die",
      location: "new_hampshire_location.jpg",
      flag: "new_hampshire_state_flag.jpg",
      county: "new_hampshire_county.gif",
      terrain: "new_hampshire_terrain.gif"
    },
    {
      name: "New Jersey",
      capital: "Trenton",
      bird: "Eastern Goldfinch",
      flower: "Purple Violet",
      area: 8721,
      order: 3,
      date: "December 18, 1787",
      nickname: "Garden State",
      motto: "Liberty and prosperity",
      location: "new_jersey_location.jpg",
      flag: "new_jersey_state_flag.jpg",
      county: "new_jersey_county.gif",
      terrain: "new_jersey_terrain.gif"
    },
    {
      name: "New Mexico",
      capital: "Santa Fe",
      bird: "Roakrunner",
      flower: "Yucca",
      area: 121589,
      order: 47,
      date: "January 6, 1912",
      nickname: "Land of Enchantment",
      motto: "Crescit eundo (It grows as it goes)",
      location: "new_mexico_location.jpg",
      flag: "new_mexico_state_flag.jpg",
      county: "new_mexico_county.gif",
      terrain: "new_mexico_terrain.gif"
    },
    {
      name: "New York",
      capital: "Albany",
      bird: "Bluebird",
      flower: "Rose",
      area: 54556,
      order: 11,
      date: "July 26, 1788",
      nickname: "Empire State",
      motto: "Crescit eundo (Ever upward)",
      location: "new_york_location.jpg",
      flag: "new_york_state_flag.jpg",
      county: "new_york_county.gif",
      terrain: "new_york_terrain.gif"
    },
    {
      name: "North Carolina",
      capital: "Raleigh",
      bird: "Cardinal",
      flower: "Dogwood",
      area: 53819,
      order: 12,
      date: "November 21, 1789",
      nickname: "Tar Heel State",
      motto: "Esse quam videri (To be, rather than to seem)",
      location: "north_carolina_location.jpg",
      flag: "north_carolina_state_flag.jpg",
      county: "north_carolina_county.gif",
      terrain: "north_carolina_terrain.gif"
    },
    {
      name: "North Dakota",
      capital: "Bismarck",
      bird: "Western Meadowlark",
      flower: "Wild Prairie Rose",
      area: 70700,
      order: 39,
      date: "November 2, 1889",
      nickname: "Sioux State; Flickertail State; Peace Garden State; Rough Rider State",
      motto: "Liberty and union, now and forever, one and inseparable",
      location: "north_dakota_location.jpg",
      flag: "north_dakota_state_flag.jpg",
      county: "north_dakota_county.gif",
      terrain: "north_dakota_terrain.gif"
    },
    {
      name: "Ohio",
      capital: "Columbus",
      bird: "Cardinal",
      flower: "Scarlet Carnation",
      area: 44825,
      order: 17,
      date: "March 1, 1803",
      nickname: "Buckeye State",
      motto: "With God, all things are possible",
      location: "ohio_location.jpg",
      flag: "ohio_state_flag.jpg",
      county: "ohio_county.gif",
      terrain: "ohio_terrain.gif"
    },
    {
      name: "Oklahoma",
      capital: "Oklahoma City",
      bird: "Scissor-Tailed Flycatcher",
      flower: "Mistletoe",
      area: 69898,
      order: 46,
      date: "November 16, 1907",
      nickname: "Sooner State",
      motto: "Labor omnia vincit (Labor conquers all things)",
      location: "oklahoma_location.jpg",
      flag: "oklahoma_state_flag.jpg",
      county: "oklahoma_county.gif",
      terrain: "oklahoma_terrain.gif"
    },
    {
      name: "Oregon",
      capital: "Salem",
      bird: "Western Meadowlark",
      flower: "Oregon Grape",
      area: 98381,
      order: 33,
      date: "February 14, 1859",
      nickname: "Beaver State",
      motto: "Alis volat propriis (She flies with her own wings)",
      location: "oregon_location.jpg",
      flag: "oregon_state_flag.jpg",
      county: "oregon_county.gif",
      terrain: "oregon_terrain.gif"
    },
    {
      name: "Pennsylvania",
      capital: "Harrisburg",
      bird: "Ruffed Grouse",
      flower: "Mountain Laurel",
      area: 46055,
      order: 2,
      date: "December 12, 1787",
      nickname: "Keystone State",
      motto: "Virtue, Liberty, and Independence",
      location: "pennsylvania_location.jpg",
      flag: "pennsylvania_state_flag.gif",
      county: "pennsylvania_county.gif",
      terrain: "pennsylvania_terrain.gif"
    },
    {
      name: "Rhode Island",
      capital: "Providence",
      bird: "Rhode Island Red",
      flower: "Violet",
      area: 1545,
      order: 13,
      date: "May 29, 1790",
      nickname: "The Ocean State",
      motto: "Hope",
      location: "rhode_island_location.jpg",
      flag: "rhode_island_state_flag.jpg",
      county: "rhode_island_county.gif",
      terrain: "rhode_island_terrain.gif"
    },
    {
      name: "South Carolina",
      capital: "Columbia",
      bird: "Great Carolina Wren",
      flower: "Carolina Yellow Jessamine",
      area: 32020,
      order: 8,
      date: "May 23, 1788",
      nickname: "Palmetto State",
      motto: "Dum spiro spero Animis opibusque parati (While I breathe, I hope Ready in soul and resource)",
      location: "south_carolina_location.jpg",
      flag: "south_carolina_state_flag.jpg",
      county: "south_carolina_county.gif",
      terrain: "south_carolina_terrain.gif"
    },
    {
      name: "South Dakota",
      capital: "Pierre",
      bird: "Ring-Necked Pheasant",
      flower: "American Pasqueflower",
      area: 77117,
      order: 40,
      date: "November 2, 1889",
      nickname: "Mount Rushmore State; Coyote State",
      motto: "Under God the people rule",
      location: "south_dakota_location.jpg",
      flag: "south_dakota_state_flag.jpg",
      county: "south_dakota_county.gif",
      terrain: "south_dakota_terrain.gif"
    },
    {
      name: "Tennessee",
      capital: "Nashville",
      bird: "Mockingbird",
      flower: "Iris",
      area: 42143,
      order: 16,
      date: "June 1, 1796",
      nickname: "Volunteer State",
      motto: "Agriculture and Commerce",
      location: "tennessee_location.jpg",
      flag: "tennessee_state_flag.gif",
      county: "tennessee_county.gif",
      terrain: "tennessee_terrain.gif"
    },
    {
      name: "Texas",
      capital: "Austin",
      bird: "Mockingbird",
      flower: "Bluebonnet",
      area: 268581,
      order: 28,
      date: "December 29, 1845",
      nickname: "Lone Star State",
      motto: "Friendship",
      location: "texas_location.jpg",
      flag: "texas_state_flag.jpg",
      county: "texas_county.gif",
      terrain: "texas_terrain.gif"
    },
    {
      name: "Utah",
      capital: "Salt Lake City",
      bird: "Common American Gull",
      flower: "Sego Lily",
      area: 84899,
      order: 45,
      date: "January 4, 1896",
      nickname: "Beehive State",
      motto: "Industry",
      location: "utah_location.jpg",
      flag: "utah_state_flag.jpg",
      county: "utah_county.gif",
      terrain: "utah_terrain.gif"
    },
    {
      name: "Vermont",
      capital: "Montepelier",
      bird: "Hermit Thrush",
      flower: "Red Clover",
      area: 9614,
      order: 14,
      date: "March 4, 1791",
      nickname: "Green Mountain State",
      motto: "Freedom and Unity",
      location: "vermont_location.jpg",
      flag: "vermont_state_flag.jpg",
      county: "vermont_county.gif",
      terrain: "vermont_terrain.gif"
    },
    {
      name: "Virginia",
      capital: "Richmond",
      bird: "Cardinal",
      flower: "Flowering Dogwood",
      area: 42774,
      order: 10,
      date: "June 25, 1788",
      nickname: "The Old Dominion; Mother of Presidents",
      motto: "Sic semper tyrannis (Thus always to tyrants)",
      location: "virginia_location.jpg",
      flag: "virginia_state_flag.jpg",
      county: "virginia_county.gif",
      terrain: "virginia_terrain.gif"
    },
    {
      name: "Washington",
      capital: "Olympia",
      bird: "Willow Goldfinch",
      flower: "Coast Rhododendron",
      area: 71300,
      order: 42,
      date: "November 11, 1889",
      nickname: "Evergreen State",
      motto: "Al-ki (By and by)",
      location: "washington_location.jpg",
      flag: "washington_state_flag.jpg",
      county: "washington_county.gif",
      terrain: "washington_terrain.gif"
    },
    {
      name: "West Virginia",
      capital: "Charleston",
      bird: "Cardinal",
      flower: "Rhododendron",
      area: 24230,
      order: 35,
      date: "June 20, 1863",
      nickname: "Mountain State",
      motto: "Montani semper liberi (Mountaineers are always free)",
      location: "west_virginia_location.jpg",
      flag: "west_virginia_state_flag.jpg",
      county: "west_virginia_county.gif",
      terrain: "west_virginia_terrain.gif"
    },
    {
      name: "Wisconsin",
      capital: "Madison",
      bird: "Robin",
      flower: "Wood Violet",
      area: 65498,
      order: 30,
      date: "May 29, 1848",
      nickname: "Badger State",
      motto: "Forward",
      location: "wisconsin_location.jpg",
      flag: "wisconsin_state_flag.jpg",
      county: "wisconsin_county.gif",
      terrain: "wisconsin_terrain.gif"
    },
    {
      name: "Wyoming",
      capital: "Cheyenne",
      bird: "Western Meadowlark",
      flower: "Indian Paintbrush",
      area: 97814,
      order: 44,
      date: "July 10, 1890",
      nickname: "Equality State",
      motto: "Equal Rights",
      location: "wyoming_location.jpg",
      flag: "wyoming_state_flag.gif",
      county: "wyoming_county.gif",
      terrain: "wyoming_terrain.gif"
    }
  ],
  selectedState: null
};
